### ISSUE TITLE
 login validation failing with correct information [Develop Branch]

### ISSUE THREAD

**Issue by NathanFortier** [Polaroid-Soen-341/SOEN341#43]
Cannot login with super user on Develop branch. Sever give the following error message.

Internal Server Error: /api-token-auth/
Traceback (most recent call last):
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\exception.py", line 
47, in inner
    response = get_response(request)
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\django\core\handlers\base.py", line 181, 
in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\views.py", line 480, in raise_uncaught_exception
    raise exc
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework_jwt\views.py", line 57, in post
    if serializer.is_valid():
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\serializers.py", line 220, in is_valid
    self._validated_data = self.run_validation(self.initial_data)
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework\serializers.py", line 422, in run_validation
    value = self.validate(value)
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework_jwt\serializers.py", line 
60, in validate
    'token': jwt_encode_handler(payload),
  File "C:\Users\Leto\AppData\Local\Programs\Python\Python39\lib\site-packages\rest_framework_jwt\utils.py", line 92, in jwt_encode_handler
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
[16/Mar/2021 20:58:24] "POST /api-token-auth/ HTTP/1.1" 500 110681

**Comment by NathanFortier** [comment]
Redundant bug, same as #41. deleting issue.
